export const ADD_BOOK='ADD_BOOK';
export const HANDLE_VALUE = 'HANDLE_VALUE';
export const CART_ADD_BOOK='CART_ADD_BOOK';
export const EDIT_BOOK_INIT='EDIT_BOOK_INIT';
export const DELETE_BOOK='DELETE_BOOK';
export const CART_DELETE_BOOK='CART_DELETE_BOOK';

export const INIT_BOOKS='INIT_BOOKS';


export const HANDLE_VALUE_DETAIL = 'HANDLE_VALUE_DETAIL'; 
export const ADD_CUSTOMER ='ADD_CUSTOMER';
export const UPLOAD_CUSTS = 'UPLOAD_CUSTS';
export const DETAIL_CUST = 'DETAIL_CUST';









export const ADD_BOOK='ADD_BOOK';
export const HANDLE_VALUE = 'HANDLE_VALUE';
export const CART_ADD_BOOK='CART_ADD_BOOK';
export const EDIT_BOOK_INIT='EDIT_BOOK_INIT';
export const DELETE_BOOK='DELETE_BOOK';
export const CART_DELETE_BOOK='CART_DELETE_BOOK';

export const INIT_BOOKS='INIT_BOOKS';


export const HANDLE_VALUE_DETAIL = 'HANDLE_VALUE_DETAIL'; 
export const ADD_CUSTOMER ='ADD_CUSTOMER';
export const UPLOAD_CUSTS = 'UPLOAD_CUSTS';
export const DETAIL_CUST = 'DETAIL_CUST';